baseURL = "https://l1nkinpark.github.io/EduFlowPlatform/"
relativeURLs = false
canonifyURLs = false
defaultContentLanguage = "vi"
defaultContentLanguageInSubdir = false
theme = "hugo-theme-learn"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
  themeVariant = "workshop"
  editURL = "https://github.com/L1nkinPark/EduFlowPlatform/edit/main/"
  description = "Báo cáo thực tập của Võ Đức Hiếu về dự án EduFlow và workshop triển khai trên AWS"
  author = "Võ Đức Hiếu"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableSearch = false

[Languages]
  [Languages.vi]
    title = "EduFlow - Báo cáo thực tập Võ Đức Hiếu"
    weight = 1
    languageName = "Tiếng Việt"

    [[Languages.vi.menu.shortcuts]]
      name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
      identifier = "aws-study-group-vi"
      url = "https://awsstudygroup.com"
      weight = 20

    [[Languages.vi.menu.shortcuts]]
      name = "<i class='fab fa-facebook'></i> AWS Study Group - Nhóm FB"
      identifier = "aws-study-group-facebook-vi"
      url = "https://www.facebook.com/groups/awsstudygroupfcj"
      weight = 20

  [Languages.en]
    title = "EduFlow - Võ Đức Hiếu Internship Report"
    weight = 2
    languageName = "English"

    [[Languages.en.menu.shortcuts]]
      name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
      identifier = "aws-study-group-en"
      url = "https://awsstudygroup.com"
      weight = 20

    [[Languages.en.menu.shortcuts]]
      name = "<i class='fab fa-facebook'></i> AWS Study Group - FB Group"
      identifier = "aws-study-group-facebook-en"
      url = "https://www.facebook.com/groups/awsstudygroupfcj"
      weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    noClasses = false
