spring.application.name=frontend

server.port=8080

spring.main.banner-mode=off

logging.level.root=warn

spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet=DEBUG
#

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=voduchieu42@gmail.com
spring.mail.password=vtsarzgdmgtcpspk

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.default-encoding=UTF-8



## Cloudinary
cloudinary.cloud_name=deu3ur8w9
cloudinary.api_key=641671634634565
cloudinary.api_secret=GUmKWZRq5yaGk8lohkYrmmImdoU
cloudinary.secure=true

# Spring i18n messages
spring.messages.basename=messages
spring.messages.encoding=UTF-8

